ALTER TABLE "SellerDaily" ADD COLUMN IF NOT EXISTS "acquiring" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SellerItemDaily" ADD COLUMN IF NOT EXISTS "acquiring" DOUBLE PRECISION NOT NULL DEFAULT 0;
